# Generated by Django 3.2.9 on 2021-11-29 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=30)),
                ('apellido_alumno', models.CharField(max_length=30)),
                ('carne', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('Municipio', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cursado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('anio', models.IntegerField()),
                ('alumnos', models.ManyToManyField(through='alumnos.Cursado', to='alumnos.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='cursado',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.curso'),
        ),
    ]
